### ISSUE TITLE
Delete of line leads to html syntax error

### ISSUE THREAD

**Issue by fabulator** [whxaxes/gulp-html-minify#2]
Hi whxaxes,

I tried your minify plugin and I have one issue. For some angular directive I use this formating of HTML for better readability.

```
<app-footer
    footer="footer"
    hotspot="appData.hotspot"
    brand="appData.brand"
    cobrand="appData.cobrand"
    >
</app-footer>
```

But when it is minified, the output is:

```
<app-footerfooter="footer"hotspot="appData.hotspot"brand="appData.brand"cobrand="appData.cobrand"></app-footer>
```

And from directive app-footer is app-footerfooter

**Comment by whxaxes** [comment]
It was fixed now, thanks for your advice

before: [https://github.com/whxaxes/gulp-html-minify/blob/master/test/ref/test2.html](https://github.com/whxaxes/gulp-html-minify/blob/master/test/ref/test2.html)<br>
after:[https://github.com/whxaxes/gulp-html-minify/blob/master/test/dist/test2.html](https://github.com/whxaxes/gulp-html-minify/blob/master/test/dist/test2.html)

**Comment by fabulator** [comment]
Thanks for quick response. It is almost perfect, but I have problem with one tag:

```
<h1
            ng-if="!brand.hideName"
            >
            {{brand.name}}
        </h1>
```

It is probably because of number in tag...

**Comment by whxaxes** [comment]
Yes, I forgot the number in tag, It's OK now  :)

**Comment by fabulator** [comment]
Great! Its working now. Thanks.
